{{ if or (eq .Values.global.deploymentMode "cluster") (eq .Values.global.deploymentMode "standby") }}
{{ if .Values.postgres.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.global.name }}-{{ .Release.Namespace }}-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.name }}-{{ .Release.Namespace }}-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.global.name }}-{{ .Release.Namespace }}-role
{{ end }}  
{{ end }}