{{ if or (eq .Values.global.deploymentMode "cluster") (eq .Values.global.deploymentMode "standby") }}
{{ if .Values.postgres.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.name }}-{{ .Release.Namespace }}-sa
{{ end }}
{{ end }}