# Iron Rain Postgres

## Demo Secrets ##
secrets:
  demo:
    postgres:
      enabled: true
      name: postgres-secrets
      
postgres:
  
  name: postgres

  standalone:
    enabled: false

  ha:
    enabled: true
    rbac:
      enabled: true
    replicas: 3
    secrets: postgres-secrets

  postgis: 
    enabled: false
    image: 
      repository: ironrainio/postgis
      tag: 12-3.1

  image:
    repository: ironrainio/postgres
    tag: 12    
  user:
    name: postgres
    # KeyName is POSTGRES_PASSWORD
    passwordSecret: postgres-secrets
  persistence:
    enabled: true
    size: 1Gi
    storageClass: 'longhorn'

pgbackrest:
  enabled: false
  restore:
    enabled: false
  backup:
    type: s3
    settings:
      retentionFull: 2
      retentionDiff: 24
    volumeConfig:
      path: ''
    s3Config:
      bucket: postgres-backup
      accessKey: minioadmin
      secretKey: minioadmin
      path: ''
      endpoint: 192.168.0.179
      port: 9000
      region: minio

pgadmin:
  enabled: true
  image:
    repository: dpage/pgadmin4
    tag: 4.29
  user:
    email: admin@localhost
    passwordSecret: postgres-secrets
  persistence:
    enabled: true
    size: 1Gi
