{{ if .Values.pgbackrest.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.name }}-pgbackrest-config
data:
  pgbackrest.conf: |
    {{ if .Values.pgbackrest.backup.enabled }}
    [database]
    db-path=/var/lib/postgresql/data/pgdata        
    repo1-s3-endpoint={{ .Values.pgbackrest.backup.s3.endpoint }}
    repo1-s3-verify-tls=n
    repo1-path=/{{ .Values.pgbackrest.backup.s3.path }}
    repo1-s3-bucket={{ .Values.pgbackrest.backup.s3.bucket }}    
    repo1-s3-key={{ .Values.pgbackrest.backup.s3.accessKey }}
    repo1-s3-key-secret={{ .Values.pgbackrest.backup.s3.secretKey }}    
    repo1-s3-region={{ .Values.pgbackrest.backup.s3.region }}
    repo1-s3-port={{ .Values.pgbackrest.backup.s3.port }}
    repo1-s3-uri-style={{ .Values.pgbackrest.backup.s3.uriStyle }}
    repo1-type=s3    
    {{ end }}

    [global]
    retention-full={{ .Values.pgbackrest.common.retentionFull }}
    retention-diff={{ .Values.pgbackrest.common.retentionDiff }}
  pgbackrest.restore.conf: |
    {{ if .Values.pgbackrest.restore.enabled }}
    [database]
    db-path=/var/lib/postgresql/data/pgdata
    repo1-s3-endpoint={{ .Values.pgbackrest.restore.s3.endpoint }}
    repo1-s3-verify-tls=n
    repo1-path=/{{ .Values.pgbackrest.restore.s3.path }}
    repo1-s3-bucket={{ .Values.pgbackrest.restore.s3.bucket }}    
    repo1-s3-key={{ .Values.pgbackrest.restore.s3.accessKey }}
    repo1-s3-key-secret={{ .Values.pgbackrest.restore.s3.secretKey }}    
    repo1-s3-region={{ .Values.pgbackrest.restore.s3.region }}
    repo1-s3-port={{ .Values.pgbackrest.restore.s3.port }}
    repo1-s3-uri-style={{ .Values.pgbackrest.restore.s3.uriStyle }}
    repo1-type=s3    
    {{ end }}  
  backup-schedule.py: |    
    #!/usr/bin/python
    import schedule
    import time
    import os

    os.system('echo "Backup operator started."')

    def job():
      os.system('pgbackrest --stanza=database --log-level-console=info backup')
    schedule.every(1).hours.do(job)

    while True:
      schedule.run_pending()
      time.sleep(1)    
{{ end }}