{{ if eq .Values.global.deploymentMode "standalone" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}-leader
  labels:
    run: {{ .Values.global.name }}-leader
spec:
  ports:
  - port: 5432
    protocol: TCP
    name: tcp-5432
  selector:
    app: {{ .Values.global.name }}-database
{{ end }}    