{{ if .Values.demo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-demo-secrets
  labels:
    note: demo-secrets
data:
  POSTGRES_PASSWORD: {{ "postgres" | b64enc }}
  PGADMIN_PASSWORD: {{ "postgres" | b64enc }}
  SUPERUSER_PASSWORD: {{ "postgres" | b64enc }}
  ADMIN_PASSWORD: {{ "postgres" | b64enc }}
  STANDBY_PASSWORD: {{ "postgres" | b64enc }}
{{ end }}
