{{ if .Values.secrets.demo.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.demo.postgres.name }}
  labels:
    note: demo-secret
data:
  POSTGRES_PASSWORD: {{ "postgres" | b64enc }}
  PGADMIN_PASSWORD: {{ "postgres" | b64enc }}
{{ end }}
