apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-svc
  labels:
    run: {{ .Values.postgres.name }}-svc
spec:
  ports:
  - port: 5432
    protocol: TCP
    name: tcp-5432
  selector:
    app: {{ .Values.postgres.name }}-app