{{ if .Values.pgadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}-pgadmin
  labels:
    deployment: {{ .Values.global.name }}-pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: {{ .Values.global.name }}-pgadmin-app
  template:
    metadata:
      annotations:
      {{- range $key, $value := .Values.postgres.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      labels:
        app: {{ .Values.global.name }}-pgadmin-app
      {{- range $key, $value := .Values.postgres.labels }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}        
    spec:
      securityContext:
        fsGroup: {{ .Values.pgadmin.securityContext.fsGroup }}        
      volumes:
      - name: {{ .Values.global.name }}-pgadmin-data
        persistentVolumeClaim:
          claimName: {{ .Values.global.name }}-pgadmin-data
      - name: {{ .Values.global.name }}-pgadmin-logs
        persistentVolumeClaim:
          claimName: {{ .Values.global.name }}-pgadmin-logs
      containers:
      - name: {{ .Values.global.name }}-pgadmin
        image: {{ .Values.pgadmin.image.repository }}:{{ .Values.pgadmin.image.tag }}
        securityContext:
          runAsUser: {{ .Values.pgadmin.securityContext.runAsUser }}
        ports:
        - containerPort: 80
          name: tcp-80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: {{ .Values.pgadmin.defaultAdmin.email }}
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgres.defaultAdmin.passwordSecret }}
              key: PGADMIN_PASSWORD
        resources:
          requests:
            cpu: {{ .Values.pgadmin.resources.requests.cpu }}
            memory: {{ .Values.pgadmin.resources.requests.memory }}
          limits:
            cpu: {{ .Values.pgadmin.resources.limits.cpu }}
            memory: {{ .Values.pgadmin.resources.limits.memory }}                 
        volumeMounts:
        - mountPath: /var/lib/pgadmin
          name: {{ .Values.global.name }}-pgadmin-data
        - mountPath: /var/log/pgadmin
          name: {{ .Values.global.name }}-pgadmin-logs
{{ end }}