{{ if .Values.pgadmin.enabled }}
{{ if .Values.pgadmin.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.name }}-pgadmin-data
spec:
  {{ if .Values.pgadmin.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pgadmin.persistence.dataSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.name }}-pgadmin-logs
spec:
  {{ if .Values.postgres.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pgadmin.persistence.logSize }}      
{{ end }}
{{ end }}