name: Postgres

on:
  push:
    branches: [ main ]

jobs:
  build-push-postgres:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1
      -
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
      - 
         name: Login to Dockerhub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}      
      - 
        name: Checkout
        uses: actions/checkout@v1
      - 
         name: Build and Push Postgres 12
         id: docker_build_pg_12     
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: ironrainio/postgres:12
           context: .
           file: containers/postgres/12/Dockerfile
           platforms: linux/amd64
      - 
         name: Build and Push Postgres 12 Patroni
         id: docker_build_pg_12_patroni         
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: ironrainio/postgres:12-patroni
           context: .
           file: containers/postgres/patroni/12/Dockerfile
           platforms: linux/amd64
      - 
         name: Build and Push Postgres 13
         id: docker_build_pg_13         
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: ironrainio/postgres:13
           context: .
           file: containers/postgres/13/Dockerfile
           platforms: linux/amd64
      - 
         name: Build and Push Postgres 13 Patroni
         id: docker_build_pg_13_patroni         
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: ironrainio/postgres:13-patroni
           context: .
           file: containers/postgres/patroni/13/Dockerfile
           platforms: linux/amd64                
  build-push-postgis:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1
      -
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
      - 
         name: Login to Dockerhub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}      
      - 
        name: Checkout
        uses: actions/checkout@v1
      - 
         name: Build and Push PostGIS 12 3.1
         id: docker_build_pg_12     
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: ironrainio/postgis:12
           context: .
           file: containers/postgis/12/Dockerfile
           platforms: linux/amd64
      - 
         name: Build and Push PostGIS 12 3.1 Patroni
         id: docker_build_pg_12_patroni         
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: ironrainio/postgis:12-patroni
           context: .
           file: containers/postgis/patroni/12/Dockerfile
           platforms: linux/amd64
      - 
         name: Build and Push PostGIS 13 3.1
         id: docker_build_pg_13         
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: ironrainio/postgis:13
           context: .
           file: containers/postgis/13/Dockerfile
           platforms: linux/amd64
      - 
         name: Build and Push PostGIS 13 3.1 Patroni
         id: docker_build_pg_13_patroni         
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: ironrainio/postgis:13-patroni
           context: .
           file: containers/postgis/patroni/13/Dockerfile
           platforms: linux/amd64                      
